### ISSUE TITLE
AttributeError exception

### ISSUE THREAD

**Issue by victor-yacovlev** [MarinaPolyakova/proglangs_Polyakova#1]
```
> python3 generate_big_graph.py
> python3 floyd_warshall.py  -f my_big_graph.graphml
```

```
Traceback (most recent call last):
  File "floyd_warshall.py", line 100, in <module>
    main()
  File "floyd_warshall.py", line 63, in main
    adjacency_matrix = [[math.inf for _ in range(len(graph._nodes))] for _ in range(len(graph._nodes))]
  File "floyd_warshall.py", line 63, in <listcomp>
    adjacency_matrix = [[math.inf for _ in range(len(graph._nodes))] for _ in range(len(graph._nodes))]
  File "floyd_warshall.py", line 63, in <listcomp>
    adjacency_matrix = [[math.inf for _ in range(len(graph._nodes))] for _ in range(len(graph._nodes))]
AttributeError: 'module' object has no attribute 'inf'

```

**Comment by MarinaPolyakova** [comment]
https://docs.python.org/3/library/math.html

math.inf
A floating-point positive infinity. (For negative infinity, use -math.inf.)
Equivalent to the output of float('inf').

New in version 3.5.
